# Makefile for gridlocke

lib.name = gridlocke

lib.setup.sources = gridlocke.c
class.sources = simple_matrix~.c changes.c pnukget.c mrg.c
make-lib-executable=yes

# datafiles = myclass1-help.pd myclass2-help.pd README.txt LICENSE.txt

PDLIBBUILDER_DIR=pd-lib-builder
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder