# Makefile for mylib

lib.name := 7m7mornings

#single file lib, very confusig at the moment
#lib.setup.sources = simple_matrix.c wow.c
#make-lib-executable=yes

simple_matrix.class.sources = simple_matrix~.c

# datafiles = myclass1-help.pd myclass2-help.pd README.txt LICENSE.txt

PDLIBBUILDER_DIR=pd-lib-builder
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder