# Makefile for mylib

lib.name = m77_test

class.sources = $(CLASS_FILES)

# datafiles = myclass1-help.pd myclass2-help.pd README.txt LICENSE.txt

PDLIBBUILDER_DIR=pd-lib-builder
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder